bk:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 11
  wechat:
    appid: wx8eb6fe83b9380ad9
    secret: b0c3a9c989985898f1c4abed927cf78c